apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "altinity-sql-browser.fullname" . }}-config
  labels:
    {{- include "altinity-sql-browser.labels" . | nindent 4 }}
data:
  # Served at /sql/config.json. Rendered from .Values.config.
  config.json: |-
    {{- .Values.config | toJson | nindent 4 }}
